### ISSUE TITLE
ijkplayer  到底怎么用呢 需要编译吗 

### ISSUE THREAD

**Issue by luhaoaimama1** [Leifzhang/ijkplayer#1]
还有人说需要NDK   我迷糊的 表示不知道如何引用官方的 lib  和demo去学习  请教啊

**Comment by Leifzhang** [comment]
的确需要so包支持 官方项目需要在linux或者mac下编译 但是可以直接用compile方式关键 如果你要用的话 可以直接引入我项目的lib库 demo 你跑一下就可以了

**Comment by luhaoaimama1** [comment]
我能加你QQ吗  我想语音下 因为我 真的不是很懂  但是希望用这个框架 。。。因为现在这个不是主流吗 而且免费  我是1149324777@qq.com

**Comment by Leifzhang** [comment]
这个只是针对客户端的解决方案而已
