### ISSUE TITLE
上传github

### ISSUE THREAD

**Issue by liy452083759** [Leifzhang/ijkplayer#10]
大神能不能发下你是怎么上传github的,跪求详细点,win7系统

**Comment by Leifzhang** [comment]
http://www.jianshu.com/p/31410d71eaba

**Comment by liy452083759** [comment]
谢谢大神

**Comment by liy452083759** [comment]
大神,关于上传出现的bug,有什么更详细的说明吗?
大神有个请求,能不能把每次编译的module.sh的发我一下,邮箱:452083759@qq.com
谢谢大神关照.
