### ISSUE TITLE
怎么降低你这个的版本？

### ISSUE THREAD

**Issue by small-tadpole** [Leifzhang/ijkplayer#4]
想直接引用compile 'com.github.leifzhang:IjkLib:0.0.1'的话，我项目的版本是22，你这个是23的，怎么调下你这个到22呢？求指教。。。。。

**Comment by Leifzhang** [comment]
compile ('com.github.leifzhang:IjkLib:0.1.0') {
        exclude module: 'appcompat-v7', group: 'com.android.support'
        exclude module: 'support-v4', group: 'com.android.support'
        exclude module: 'design', group: 'com.android.support'
    }
 你可以尝试下这种方式
