### ISSUE TITLE
播放rtmp 直播流延迟非常严重

### ISSUE THREAD

**Issue by FrankLove** [Leifzhang/ijkplayer#7]
1、为什么播放rtmp 直播流延迟非常严重呢？一开始进去大概就是15秒的延迟，同样的网络用其他人编译的ijkplayer没有这样
2、播放视频有时候会突然进入activity的onpause()方法，接着又进入onresume。

**Comment by Leifzhang** [comment]
https://github.com/Bilibili/ijkplayer/issues/210 
这个是在ijkplayer 找到的相关rtmp的延迟的资料 可以参考下

**Comment by crazy1235** [comment]
这个库有丢帧策略吗？
