### ISSUE TITLE
视频竖屏暂停的情况下旋转屏幕会自动播放

### ISSUE THREAD

**Issue by FrankLove** [Leifzhang/ijkplayer#9]
视频竖屏暂停的情况下，如果旋转屏幕到横盘会自动播放，已经在播放的activity里面配置了
 android:configChanges="keyboardHidden|orientation|screenSize"，请问这是什么原因

**Comment by Leifzhang** [comment]
mSHCallback  有可能是这个类导致的

**Comment by FrankLove** [comment]
@Leifzhang 修改了你封装的类，现在可以了
